export const nfts = {
  CryptoPunks: "cryptopunks",
  "Bored Ape Yacht Club": "bored-ape-yacht-club",
  Sorare: "sorare",
  Otherdeed: "otherdeed",
  "Mutant Ape Yacht Club": "mutant-ape-yacht-club",
  "Art Blocks": "art-blocks",
  Potatoz: "potatoz",
  Moonbirds: "moonbirds",
  CloneX: "clonex",
  "Moonbirds Oddities": "moonbirds-oddities",
  Doodles: "doodles",
  "NBA Top Shot": "nba-top-shot",
  "Ledger Market Pass - Genesis Edition":
    "ledger-market-pass---genesis-edition",
  "Ethereum Name Service": "ethereum-name-service",
  "Super Cool World": "super-cool-world",
  Meebits: "meebits",
  "YOLO Bunny": "yolo-bunny",
  Azuki: "azuki",
  goblintown: "goblintown",
  "Isekai Meta": "isekai-meta",
  STEPNNFT: "stepnnft",
  ElectricSheep: "electricsheep",
  "Axie Infinity": "axie-infinity",
  "Bored Ape Kennel Club": "bored-ape-kennel-club",
  NFTiff: "nftiff",
  "Factura by Mathias Isaksen": "factura-by-mathias-isaksen",
  "Rags to Richie by Alec Monopoly": "rags-to-richie-by-alec-monopoly",
  "Panini America": "panini-america",
  YOLO: "yolo",
  "CubeX NFTs": "cubex-nfts",
  "Bored--Dangerous": "bored--dangerous",
  "NFL All Day": "nfl-all-day",
  mcgoblinwtf: "mcgoblinwtf",
  MEGAMI: "megami",
  "Amazy Sneaker": "amazy-sneaker",
  "The Possessed": "the-possessed",
  "NFT Worlds": "nft-worlds",
  KINGSHIP: "kingship",
  Froots: "froots",
  "Parallel Alpha": "parallel-alpha",
  Rakkudo: "rakkudo",
  Nickelodeon: "nickelodeon",
  ImmortalPlayerCharacter: "immortalplayercharacter",
  "The Currency Eth": "the-currency-eth",
  "Okay Bears": "okay-bears",
  PolkamonOfficialCollection: "polkamonofficialcollection",
  "Pudgy Penguins": "pudgy-penguins",
  "God Hates NFTees": "god-hates-nftees",
  Miningverse: "miningverse",
  KILLABEARS: "killabears",
  DeGods: "degods",
  "Tableland Rigs": "tableland-rigs",
  "GODA Mint Pass": "goda-mint-pass",
  "Primate Academy": "primate-academy",
  MurakamiFlowers: "murakamiflowers",
  "Stickmen Toys": "stickmen-toys",
  "Collab Kyzen 7 Character Reveals": "project-kyzen-7-character-reveals",
  mfer: "mfer",
  "CryptoDickbutts S3": "cryptodickbutts-s3",
  "Life goes on": "life-goes-on",
  "Town Star": "town-star",
  VeeFriends: "veefriends",
  "Degen Fat Cat": "degen-fat-cat",
  "Etherjump Plots": "etherjump-plots",
  Zenogakki: "zenogakki",
  "gmDAO Token v2": "gmdao-token-v2",
  "Theirsverse Official": "theirsverse-official",
  "Marvion VhNFTs v1": "marvion-vhnfts-v1",
  Mooncatz: "mooncatz",
  "Cool Cats": "cool-cats",
  "Degen Degen": "degen-degen",
  "Mystics Universe": "mystics-universe",
  Jiraverse: "jiraverse",
  "Collab 0xD38": "project-0xd38",
  "Emblem Vault": "emblem-vault",
  Beanz: "beanz",
  "Grumpy Dragon": "grumpy-dragon",
  "Admit One": "admit-one",
  Dooplicator: "dooplicator",
  "VeeFriends Series 2": "veefriends-series-2",
  ESION: "esion",
  Illuminati: "illuminati",
  "Tubby Cats": "tubby-cats",
  Chimpers: "chimpers",
  aidegens: "aidegens",
  "Day of Right club token": "day-of-right-club-token",
  "Gods Unchained Immutable": "gods-unchained-immutable",
  Terraforms: "terraforms",
  "Mirakai Scrolls": "mirakai-scrolls",
  FGDNFT: "fgdnft",
  "Raccoon Network NFT Token": "raccoon-network-nft-token",
  "Candy Digital NFT": "candy-digital-nft",
  Decagon: "decagon",
  Musicape: "musicape",
  "14041 Mutant Apes": "14041-mutant-apes",
  "V1 Cryptopunks Wrapped": "v1-cryptopunks-wrapped",
  Lord: "lord",
  "World Of Women": "world-of-women",
  "Rtfkt Nike x Monolith": "rtfkt-nike-x-monolith",
  "10KTF": "10ktf",
};
